force-app/main/default/objects/Song__c/fields/Album_Id__c.field-meta.xml
<CustomField>
    <fullName>Album_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Album_Id</label>
    <referenceTo>Album__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Songs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/Artist_Id__c.field-meta.xml
<CustomField>
    <fullName>Artist_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Artist_Id</label>
    <referenceTo>Artist__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>Songs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SongSelector.cls
public with sharing class SongSelector {
     public static List<Song__c> getUpcomingSongs() {
        return [
            SELECT Id, Name, Album_Id__c, Artist_Id__c, Release_Date__c, Duration__c
            FROM Song__c
            WHERE Release_Date__c > :Date.today()
            ORDER BY Release_Date__c ASC
        ];
    }

    public static List<Song__c> getNextSongs(Integer limitSize) {
        return [
            SELECT Id, Name, Album_Id__c, Artist_Id__c, Release_Date__c, Duration__c
            FROM Song__c
            WHERE Release_Date__c >= :Date.today()
            ORDER BY Release_Date__c ASC
            LIMIT :limitSize
        ];
    }

    public static List<Song__c> getSongsFromAlbum(Id albumId) {
        return [
            SELECT Id, Name, Album_Id__c, Artist_Id__c, Release_Date__c, Duration__c
            FROM Song__c
            WHERE Album_Id__c = :albumId
            ORDER BY Release_Date__c ASC
        ];
    }
    public SongSelector() {

    }
}